version: '3'
services:
  service-registry:
    container_name: service-registry
    image: service-registry
    ports:
      - "8761:8761"

  user-service:
    container_name: user-service
    image: user-service
    ports:
      - "8080:8080"
    depends_on:
      - service-registry
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres://user:0Gb3bd8zx0CjzxTXZCSdxvYFWPwnwGw0@dpg-clgnf37jc5ks73eghor0-a.oregon-postgres.render.com/postgres_db_wshe
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: 0Gb3bd8zx0CjzxTXZCSdxvYFWPwnwGw0