server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: menu-service
          uri: lb://menu-service
          predicates:
            - Path=/menu/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
        - id: user-service
          uri: lb://order-service
          predicates:
            - Path=/order/**